### ISSUE TITLE
Revise survey questions

### ISSUE THREAD

**Issue by UppaJung** [cxhercules/password-manager-dashboards#1]

**Comment by UppaJung** [comment]
@jackyh0 will propose ways to put Stuart's survey question suggestion into a more detailed proposal

**Comment by jackyh0** [comment]
Added and updated questions
Pending: Shortlist the list of the password manager to 5

**Comment by cristianbravolillo** [comment]
This task will be managed in Pivotal (https://www.pivotaltracker.com/n/projects/2481726).
